# Generated by Django 3.1.2 on 2020-10-11 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='Name',
            new_name='name',
        ),
    ]
