# Generated by Django 3.1.2 on 2020-10-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Categories',
        ),
        migrations.AddField(
            model_name='image',
            name='Categories',
            field=models.ManyToManyField(to='photos.Categories'),
        ),
    ]
